#端口号
server:
  port: 8890

spring:
  # 数据库连接池 (DataSource) 配置
  datasource:
    url: jdbc:mysql://localhost:3306/aiweb
    # 数据库用户名 (通常是 root)
    username: root
    # 您的数据库密码 (请替换成您自己的密码)
    password: Zj17320321853@
    # MySQL 8+ 的驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  # 密钥
  secret: '2qUSpwm/nO1N54p4BWMIO/8vU+hFYObj4490oUcKpMc='
  # 过期时间 (例如 12 小时)
  expiration: 43200000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

smsbao:
  apiurl: http://api.smsbao.com/sms
  username: aiweb
  password: Zj123456@
  contentSign: Aiweb



